version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_SECURE_COOKIE=false   # necesario para correr en local sin HTTPS
      - GENERIC_TIMEZONE=America/Santiago
      - TZ=America/Santiago
    volumes:
      - ./.n8n_data:/home/node/.n8n
    restart: unless-stopped
